# Generated by Django 3.1 on 2020-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200811_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]
