# Generated by Django 3.1 on 2021-06-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('img_link', models.CharField(max_length=1000)),
                ('duration', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('teacher', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
    ]
