# Generated by Django 3.1 on 2021-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='last_date',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='courses',
            name='payment_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.CharField(max_length=15),
        ),
    ]
