# Generated by Django 3.1 on 2021-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20210602_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('img_link', models.CharField(max_length=1000)),
                ('instructor_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('skills', models.CharField(max_length=150)),
                ('instagram_link', models.CharField(max_length=150)),
                ('linkedin_link', models.CharField(max_length=150)),
            ],
        ),
    ]
