# Generated by Django 3.1 on 2021-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('img_link', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('testimonial', models.CharField(max_length=256)),
            ],
        ),
    ]
