# Generated by Django 3.1 on 2020-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200818_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('winner_id', models.AutoField(primary_key=True, serialize=False)),
                ('winner_name', models.CharField(default='', max_length=100)),
                ('winner_desc', models.TextField()),
                ('image', models.ImageField(default='', upload_to='static/w&c')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
