# Generated by Django 3.1 on 2020-08-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_urls',
            field=models.CharField(default='', max_length=100),
        ),
    ]
