# Generated by Django 3.1 on 2020-08-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=100)),
                ('announcement_desc', models.TextField()),
                ('link', models.CharField(max_length=400)),
                ('image', models.ImageField(default='', upload_to='static/annoucement')),
            ],
        ),
    ]
