# Generated by Django 3.1 on 2020-08-26 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='about_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
