# Generated by Django 3.1 on 2020-08-28 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200828_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='image',
        ),
        migrations.AddField(
            model_name='winner',
            name='img_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
