# Generated by Django 3.1 on 2021-05-22 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20200828_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_profile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('edu_qul', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=13)),
                ('wmobile', models.CharField(max_length=13)),
                ('talent', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('user_name', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
