# Generated by Django 3.1 on 2021-05-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_update_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update_profile',
            name='talent',
        ),
        migrations.AddField(
            model_name='update_profile',
            name='request_of_update',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='update_profile',
            name='teacher',
            field=models.CharField(default='', max_length=30),
        ),
    ]
