# Generated by Django 3.1 on 2021-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210522_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_profile',
            name='request_of_update',
            field=models.CharField(max_length=10),
        ),
    ]
