# Generated by Django 3.1 on 2021-05-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210522_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='winner',
            name='url_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='winner',
            name='img_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
