# Generated by Django 3.1 on 2021-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210531_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_profile',
            name='remark',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
