# Generated by Django 3.1 on 2021-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_update_profile_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_profile',
            name='img_link',
            field=models.CharField(default='https://bootdey.com/img/Content/avatar/avatar7.png', max_length=200),
        ),
    ]
