# Generated by Django 3.1 on 2021-06-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0024_auto_20210531_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_profile',
            name='are_of_working_in_metaeducator',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='are_we_helping_in_project',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='are_you_doing_intrenship_through_metaeducator',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='project_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='update_profile',
            name='remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Correction_form',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('correction', models.CharField(max_length=500)),
                ('user_name', models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
