# Generated by Django 3.1 on 2020-08-25 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('video_title', models.CharField(max_length=300)),
                ('video_desc', models.TextField()),
                ('playlist_title', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(default='', max_length=250, unique=True)),
                ('video_link', models.CharField(default='', max_length=250, unique=True)),
                ('image', models.FileField(default='', upload_to='static/video/playvideo')),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='videocomment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.videocomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video')),
            ],
        ),
    ]
