# Generated by Django 3.1 on 2020-08-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='slug',
            new_name='sluger',
        ),
    ]
