# Generated by Django 3.1 on 2020-08-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200825_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='sluger',
            new_name='slug',
        ),
    ]
