# Generated by Django 3.1 on 2020-09-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_auto_20200828_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='img_link',
        ),
    ]
