# Generated by Django 3.1 on 2020-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_remove_video_img_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ytlist',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('ytlist_desc', models.TextField()),
                ('ytlist_title', models.CharField(default='', max_length=200)),
                ('slug', models.CharField(default='', max_length=250, unique=True)),
                ('img_link', models.CharField(max_length=5000)),
            ],
        ),
    ]
