# Generated by Django 3.1 on 2020-09-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_auto_20200913_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='number',
            new_name='num',
        ),
    ]
