# Generated by Django 3.1 on 2020-09-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0010_auto_20200913_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='num',
        ),
    ]
