# Generated by Django 3.1 on 2020-09-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_remove_video_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
