# Generated by Django 3.1 on 2020-09-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0012_video_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='no',
            field=models.IntegerField(default='0'),
        ),
    ]
