# Generated by Django 3.1 on 2020-09-13 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_video_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='no',
        ),
        migrations.RemoveField(
            model_name='video',
            name='number',
        ),
        migrations.AddField(
            model_name='video',
            name='num',
            field=models.IntegerField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
