# Generated by Django 3.1 on 2020-09-13 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0015_auto_20200913_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='num',
        ),
        migrations.AddField(
            model_name='video',
            name='number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
